[workspace]
members = [
  "core",
  "node",
]

[profile.dev]
debug       = 2
incremental = true

[profile.release]
codegen-units = 1
debug         = false
incremental   = true
lto           = false
opt-level     = 3
