[package]
name = "rs_glob"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob_match = { path = "../glob-match" }
git2 = "0.16.0"
