/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function glob(pattern: string, st: string): boolean
export function rsGlob(pattern: string): Promise<Array<string>>
export function hhh(pattern: string): Promise<Array<string>>
